name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: dotnet restore
      run: dotnet restore
    - name: dotnet build
      run: dotnet build --configuration Release --no-restore
    - name: dotnet test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish NuGet
      id: publish_nuget
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: alirezanet/publish-nuget@v3.1.0
      with:
        PROJECT_FILE_PATH: dotnet-json/dotnet-json.csproj
        PACKAGE_NAME: dotnet-json
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
    - name: Create release
      id: create_release
      if: success() && steps.publish_nuget.outputs.version != ''
      run: gh release create ${{ steps.publish_nuget.outputs.version }} --generate-notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish dotnet-json executables
      if: success() && steps.publish_nuget.outputs.version != ''
      run: |
        dotnet publish -c Release -o ./output/win --self-contained true -r win-x86 -p:PublishSingleFile=true -p:PublishTrimmed=true
        mv ./output/win/dotnet-json.exe ./output/dotnet-json.exe
        dotnet publish -c Release -o ./output/linux --self-contained true -r linux-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true
        mv ./output/linux/dotnet-json ./output/dotnet-json-linux
        dotnet publish -c Release -o ./output/osx --self-contained true -r osx-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true
        mv ./output/osx/dotnet-json ./output/dotnet-json-osx
    - name: Upload release assets
      if: success() && steps.publish_nuget.outputs.version != ''
      run: gh release upload ${{ steps.publish_nuget.outputs.version }} ./output/dotnet-json.exe ./output/dotnet-json-linux ./output/dotnet-json-osx
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
