name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish NuGet
      id: publish_nuget
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: alirezanet/publish-nuget@v3.0.4
      with:
        PROJECT_FILE_PATH: dotnet-json/dotnet-json.csproj
        PACKAGE_NAME: dotnet-json
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
    - name: Create release
      id: create_release
      if: success() && steps.publish_nuget.outputs.version != ''
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.publish_nuget.outputs.version }}
        release_name: ${{ steps.publish_nuget.outputs.version }}
        body: ""
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish dotnet-json executables
      if: success() && steps.publish_nuget.outputs.version != ''
      run: |
        dotnet publish -c Release -o ./output/win --self-contained true -r win-x86 -p:PublishSingleFile=true -p:PublishTrimmed=true
        dotnet publish -c Release -o ./output/linux --self-contained true -r linux-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true
        dotnet publish -c Release -o ./output/osx --self-contained true -r osx-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true
    - name: Upload windows release asset
      if: success() && steps.publish_nuget.outputs.version != ''
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/win/dotnet-json.exe
        asset_name: dotnet-json.exe
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload linux release asset
      if: success() && steps.publish_nuget.outputs.version != ''
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/linux/dotnet-json
        asset_name: dotnet-json-linux
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload osx release asset
      if: success() && steps.publish_nuget.outputs.version != ''
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/osx/dotnet-json
        asset_name: dotnet-json-osx
        asset_content_type: application/json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
