name: PR validation

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json
    - name: dotnet restore
      run: dotnet restore
    - name: dotnet build
      run: dotnet build --configuration Release --no-restore
    - name: dotnet test
      run: dotnet test --no-restore --verbosity normal
